///|
let grass_probabilities : Array[UInt] = [
  20, 20, 10, 10, 10, 10, 5, 5, 4, 4, 1, 1,
]

///|
let surf_probabilities : Array[UInt] = [60, 30, 5, 4, 1]

///|
let old_rod_probabilities : Array[UInt] = [70, 30]

///|
let good_rod_probabilities : Array[UInt] = [60, 20, 20]

///|
let super_rod_probabilities : Array[UInt] = [40, 40, 15, 4, 1]

///|
let rock_smash_probabilities : Array[UInt] = [60, 30, 5, 4, 1]
